### ISSUE TITLE
Can't perform rake jobs:work

### ISSUE THREAD

**Issue by SergeyKishenin** [collectiveidea/delayed_job_data_mapper#12]
Getting an error:

``` bash
$ rake jobs:work
syck has been removed, psych is used instead
[Worker(host:sergey-K50IJ pid:20241)] Starting job worker
[Worker(host:sergey-K50IJ pid:21280)] Hash failed with NoMethodError: undefined method `perform' for #<Hash:0x9be9d2c> - 5 failed attempts
rake aborted!
undefined method `sum' for [0, 0]:Array
/home/sergey/.rvm/gems/ruby-2.0.0-p247/gems/delayed_job-2.1.4/lib/delayed/worker.rb:81:in `block in start'
/home/sergey/.rvm/gems/ruby-2.0.0-p247/gems/delayed_job-2.1.4/lib/delayed/worker.rb:74:in `loop'
/home/sergey/.rvm/gems/ruby-2.0.0-p247/gems/delayed_job-2.1.4/lib/delayed/worker.rb:74:in `start'
/home/sergey/.rvm/gems/ruby-2.0.0-p247/gems/delayed_job-3.0.5/lib/delayed/tasks.rb:9:in `block (2 levels) in <top (required)>'
/home/sergey/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `eval'
/home/sergey/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `<main>'

```

I do:

``` ruby
  def perform
    store(dump)
    cleanup
  end
  handle_asynchronously :perform
```

A job is stored but can't be executed.

I'm using Sinatra, Ruby 2.0.0, the egde version of delayed_job_data_mapper and 1.2.0 version of datamapper

**Comment by tpitale** [comment]
@SergeyKishenin are you still experiencing this issue?

**Comment by asheren** [comment]
Hi there! We’re doing some open source maintenance work and closing old issues. If you would still like this issue to be addressed, please re-create it by May 17, 2017. Thanks!
